# Generated by Django 5.1.1 on 2024-09-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='soil_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
