# Generated by Django 5.1.1 on 2024-11-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FloodRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255, unique=True)),
                ("risk_percentage", models.JSONField()),
                ("soil_type", models.CharField(max_length=100)),
                ("elevation", models.FloatField()),
                ("geometry", models.JSONField(null=True)),
            ],
        ),
    ]
