# Generated by Django 5.1.1 on 2024-11-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood_risk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floodrisk",
            name="risk_percentage",
            field=models.JSONField(),
        ),
    ]
